# Generated by Django 4.2.7 on 2023-11-29 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_board_regdate'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='board',
        #     name='regdate',
        #     field=models.DateTimeField(default=django.utils.timezone.now),
        # ),
        # migrations.AddField(
        #     model_name='board',
        #     name='writer',
        #     field=models.CharField(default=django.utils.timezone.now, max_length=50),
        #     preserve_default=False,
        # ),
    ]
