# Generated by Django 4.2.7 on 2023-12-03 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_board_regdate_board_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_date_field', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='regdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='board',
            name='writer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
