# Generated by Django 4.2.7 on 2023-12-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_mymodel_reference_board_regdate_board_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
