# Generated by Django 4.2.7 on 2023-12-19 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='regdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
