# Generated by Django 4.2.7 on 2023-12-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_post_regdate_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reference_files/'),
        ),
    ]
