# Generated by Django 4.2.7 on 2023-12-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_reference_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reference',
            name='file',
            field=models.FileField(upload_to='reference_files/'),
        ),
    ]
