# Generated by Django 4.2.7 on 2023-12-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_board_view_cnt_alter_reference_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
