# Generated by Django 4.2.7 on 2024-01-01 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_reference_view_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
