# Generated by Django 4.2.7 on 2024-01-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_board_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='board_reply',
            name='board_no',
            field=models.IntegerField(default=0),
        ),
    ]
