# Generated by Django 4.2.7 on 2024-01-04 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_board_reply_board_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writer', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('board_no', models.IntegerField(default=0)),
            ],
        ),
    ]
