# Generated by Django 4.2.7 on 2024-01-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_reference_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_reply',
            old_name='board_no',
            new_name='reference_no',
        ),
    ]
